### ISSUE TITLE
Indicator is missing

### ISSUE THREAD

**Issue by addicted2sounds** [GGleb/indicator-systemtray-unity#1]
I found that indicator is missing. Is there any updates\fixes for that?

**Comment by GGleb** [comment]
In both modes (near the indicator, and separate from it)?
Version of the indicator: "0.2"?

**Comment by addicted2sounds** [comment]
I've already found that was disabled in setting for some reason. dconf-editor helped to resolve the problem

**Comment by GGleb** [comment]
What was disabled? What key and what value?

**Comment by addicted2sounds** [comment]
the option 'disable-indicator' was checked. I'm not sure how that happened
