### ISSUE TITLE
Feature Request: Background for icons

### ISSUE THREAD

**Issue by niberius** [GGleb/indicator-systemtray-unity#2]
Hello.

Thank you for indicator. But have one wish :)
Is it hard to implement optional background for tray icons? If not, can you do it please? In my opinion that is not comfortable when icons just stay overlayed on top of other applications like something foreign in the system)
http://i.imgur.com/6JYRwDn.png

**Comment by GGleb** [comment]
OK. I will try to do within two weeks.

**Comment by GGleb** [comment]
Do you like this view?
![scrnsht](https://cloud.githubusercontent.com/assets/10351130/7888831/c4903dae-0654-11e5-96dc-fee2e2bde287.png)

**Comment by niberius** [comment]
I think it's better than now. But can you reduce a transparancy? Or maybe make it optional in percents or some other units?

**Comment by GGleb** [comment]
Color can be changed optionally.

**Comment by niberius** [comment]
Oh, so that's cool, thanks! When the new version will be available in your PPA? :)

**Comment by GGleb** [comment]
Soon will be. Still need to test. Had to tweak the main library.

**Comment by GGleb** [comment]
Done!
