### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by rcspam** [GGleb/indicator-systemtray-unity#4]
Hi GGleb,
Impossible to me to change background color.
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/8000913/a5f15e6c-0b60-11e5-9eea-16a49b10dba6.png)

Can you give me a link to download 0.2 version?
Thanx

**Comment by GGleb** [comment]
The background can be disabled:
Run in terminal:
gsettings set net.launchpad.indicator.systemtray show-background-static false

Or:
In the menu of the indicator: Settings->Background->Static->Show (Uncheck).

**Comment by GGleb** [comment]
Or still need the old version?

**Comment by rcspam** [comment]
No thank you, it's ok now !
